// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHd8fbbkJQgrtbliUvM7OPrFKSRofEAIE',
    appId: '1:552426657183:web:00602a4659ed4b8b6399aa',
    messagingSenderId: '552426657183',
    projectId: 'mindset-etk',
    authDomain: 'mindset-etk.firebaseapp.com',
    storageBucket: 'mindset-etk.firebasestorage.app',
    measurementId: 'G-N97LV768PB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI489m3_55FW9qWT9e9OD63hFLChCjx0s',
    appId: '1:552426657183:android:e4e69095edac4b196399aa',
    messagingSenderId: '552426657183',
    projectId: 'mindset-etk',
    storageBucket: 'mindset-etk.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9BMedfJ222TK7xnzP-pw9PNorooRgyLk',
    appId: '1:552426657183:ios:146300367177503c6399aa',
    messagingSenderId: '552426657183',
    projectId: 'mindset-etk',
    storageBucket: 'mindset-etk.firebasestorage.app',
    iosBundleId: 'com.example.mindset',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9BMedfJ222TK7xnzP-pw9PNorooRgyLk',
    appId: '1:552426657183:ios:146300367177503c6399aa',
    messagingSenderId: '552426657183',
    projectId: 'mindset-etk',
    storageBucket: 'mindset-etk.firebasestorage.app',
    iosBundleId: 'com.example.mindset',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHd8fbbkJQgrtbliUvM7OPrFKSRofEAIE',
    appId: '1:552426657183:web:580d527f9ac3db986399aa',
    messagingSenderId: '552426657183',
    projectId: 'mindset-etk',
    authDomain: 'mindset-etk.firebaseapp.com',
    storageBucket: 'mindset-etk.firebasestorage.app',
    measurementId: 'G-2CLRGWD0DL',
  );
}
